require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.2.2
  Exclude:
   - "bin/*"
   - config/boot.rb
   - config/environment.rb
   - config/initializers/**
   - config/environments/**
   - db/schema.rb
   - db/migrate/**
   - "node_modules/**/*"
   - "bower_components/**/*"
   - "tmp/**/*"
   - "vendor/**/*"
   - Gemfile


Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"
    - "config/environments/production.rb"
    - "app/admin/*"
    - "lib/tasks/**"
Metrics/ClassLength:
  Enabled: false


Metrics/MethodLength:
  Max: 30


Layout/LineLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/VariableNumber:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 14

RSpec/ExampleLength:
  Max: 20

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**"

Rails/RefuteMethods:
  Enabled: false

Rails/Validation:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test


Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/RescueStandardError:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
