{
  "swagger": "2.0",
  "info": {
    "title": "HotelDesk API DOC",
    "version": "v1"
  },
  "components": {
    "securityDefinitions": {
      "Bearer": {
        "description": "...",
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "paths": {
    "/api/v1/users/login.json": {
      "post": {
        "summary": "User Login",
        "tags": [
          "users"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password"
              ],
              "properties": {
                "user": {
                  "type": "object",
                  "description": "user mail ",
                  "properties": {
                    "email": {
                      "type": "string",
                      "description": "user mail",
                      "example": "email@haider.com"
                    },
                    "password": {
                      "type": "string",
                      "description": "user password",
                      "example": "123456789"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login Success",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "attributes": {
                  "type": "hash"
                }
              },
              "required": [
                "id",
                "attributes"
              ]
            }
          },
          "401": {
            "description": "Login Failed"
          }
        }
      }
    },
    "/api/v1/users/signup.json": {
      "post": {
        "summary": "User SignUp",
        "tags": [
          "users"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password"
              ],
              "properties": {
                "user": {
                  "type": "object",
                  "description": "user mail ",
                  "properties": {
                    "email": {
                      "type": "string",
                      "description": "user mail",
                      "example": "email@haider.com"
                    },
                    "password": {
                      "type": "string",
                      "description": "user password",
                      "example": "123456789"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "SignUp Success"
          },
          "422": {
            "description": "SignUp Failed"
          }
        }
      }
    },
    "/api/v1/users/signup": {
      "delete": {
        "summary": "User delete",
        "tags": [
          "users"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "password",
            "in": "query",
            "type": "string",
            "required": true,
            "example": "qWzBB4IiLBzJ"
          }
        ],
        "responses": {
          "200": {
            "description": "Deleted Success"
          },
          "422": {
            "description": "Deleted Failed"
          }
        }
      }
    },
    "/api/v1/users/logout": {
      "delete": {
        "summary": "User Logout",
        "tags": [
          "users"
        ],
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "in": "header",
            "type": "string",
            "name": "Authorization",
            "required": true,
            "description": "Client token"
          }
        ],
        "responses": {
          "200": {
            "description": "Logout Success"
          },
          "401": {
            "description": "Logout Failed"
          }
        }
      }
    },
    "/api/v1/users/password": {
      "post": {
        "summary": " Forget Password Request",
        "tags": [
          "users"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "email"
              ],
              "properties": {
                "user": {
                  "type": "object",
                  "description": "user mail ",
                  "properties": {
                    "email": {
                      "type": "string",
                      "description": "user mail",
                      "example": "email@haider.com"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Forget password Success"
          },
          "422": {
            "description": "Failed"
          }
        }
      },
      "patch": {
        "summary": " Rest Password Request",
        "tags": [
          "users"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "password",
                "reset_password_token",
                "password_confirmation"
              ],
              "properties": {
                "user": {
                  "type": "object",
                  "description": "user details ",
                  "properties": {
                    "reset_password_token": {
                      "type": "string",
                      "description": "user mail ",
                      "example": "TOKEN_HERE"
                    },
                    "password": {
                      "type": "string",
                      "description": "user password",
                      "example": "123456789"
                    },
                    "password_confirmation": {
                      "type": "string",
                      "description": "user password",
                      "example": "123456789"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Rest password Success"
          },
          "422": {
            "description": "Failed"
          }
        }
      }
    },
    "/api/v1/reservation": {
      "post": {
        "summary": "create reservation",
        "tags": [
          "reservation"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "header",
            "type": "string",
            "name": "Authorization",
            "required": true,
            "description": "user Barer token"
          },
          {
            "name": "reservation",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "reservation": {
                  "type": "object",
                  "description": "user mail ",
                  "properties": {
                    "room_id": {
                      "type": "integer",
                      "description": "",
                      "example": "room id"
                    },
                    "guests_count": {
                      "type": "integer",
                      "description": "guests count",
                      "example": 2
                    },
                    "end_date": {
                      "type": "string",
                      "description": "capacity count guests",
                      "example": "2022-10-10"
                    },
                    "start_date": {
                      "type": "string",
                      "example": "2022-10-1"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "reservation Success",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "attributes": {
                  "type": "hash"
                }
              },
              "required": [
                "id",
                "attributes"
              ]
            }
          },
          "401": {
            "description": "reservation Failed"
          }
        }
      },
      "get": {
        "summary": "list of rooms",
        "tags": [
          "reservation"
        ],
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "name": "per_page",
            "in": "query",
            "type": "string",
            "required": false,
            "example": 10
          },
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "required": true,
            "example": 1
          },
          {
            "name": "start_date",
            "in": "query",
            "type": "integer",
            "required": false,
            "example": 1
          },
          {
            "name": "end_date",
            "in": "query",
            "type": "integer",
            "required": false,
            "example": 5
          },
          {
            "in": "header",
            "type": "string",
            "name": "Authorization",
            "required": true,
            "description": "user Barer token"
          }
        ],
        "responses": {
          "200": {
            "description": "Room Success"
          }
        }
      }
    },
    "/api/v1/room": {
      "post": {
        "summary": "create room",
        "tags": [
          "rooms"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "header",
            "type": "string",
            "name": "Authorization",
            "required": true,
            "description": "user Barer token"
          },
          {
            "name": "room",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "room": {
                  "type": "object",
                  "description": "user mail ",
                  "properties": {
                    "description": {
                      "type": "string",
                      "description": "",
                      "example": "details for room"
                    },
                    "price": {
                      "type": "decimal",
                      "description": "price room",
                      "example": 20
                    },
                    "capacity": {
                      "type": "integer",
                      "description": "capacity count guests",
                      "example": 3
                    },
                    "room_type_id": {
                      "type": "integer",
                      "example": 1
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login Success",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "attributes": {
                  "type": "hash"
                }
              },
              "required": [
                "id",
                "attributes"
              ]
            }
          },
          "401": {
            "description": "Login Failed"
          }
        }
      },
      "get": {
        "summary": "list of rooms",
        "tags": [
          "rooms"
        ],
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "name": "per_page",
            "in": "query",
            "type": "string",
            "required": false,
            "example": 10
          },
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "required": true,
            "example": 1
          },
          {
            "name": "price_gt",
            "in": "query",
            "type": "integer",
            "required": false,
            "example": 1
          },
          {
            "name": "price_less",
            "in": "query",
            "type": "integer",
            "required": false,
            "example": 5
          },
          {
            "name": "room_type_id",
            "in": "query",
            "type": "integer",
            "required": false
          },
          {
            "in": "header",
            "type": "string",
            "name": "Authorization",
            "required": true,
            "description": "user Barer token"
          }
        ],
        "responses": {
          "200": {
            "description": "Room Success"
          }
        }
      }
    },
    "/api/v1/room/{id}": {
      "get": {
        "summary": "get room info",
        "tags": [
          "rooms"
        ],
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "in": "header",
            "type": "string",
            "name": "Authorization",
            "required": true,
            "description": "user Barer token"
          },
          {
            "name": "id",
            "in": "path",
            "type": "integer",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "room Success"
          },
          "404": {
            "description": "room Not Found"
          }
        }
      }
    },
    "/api/v1/room_type": {
      "get": {
        "summary": "list of rooms",
        "tags": [
          "rooms"
        ],
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "name": "per_page",
            "in": "query",
            "type": "string",
            "required": false,
            "example": 10
          },
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "required": true,
            "example": 1
          },
          {
            "in": "header",
            "type": "string",
            "name": "Authorization",
            "required": true,
            "description": "user Barer token"
          }
        ],
        "responses": {
          "200": {
            "description": "Room Success"
          }
        }
      }
    }
  }
}